-- =====================================================================
-- BULK EXECUTIONS — Rastreamento de criações em massa
-- =====================================================================
-- Execute no Supabase SQL Editor após o schema principal.
-- Consistente com schema_facebook_ads_manager.sql:
--   • ID sequencial (BIGINT), sem user_id
--   • RLS authenticated_all (qualquer usuário logado)
-- =====================================================================

CREATE TABLE IF NOT EXISTS facebook_ads_manager.bulk_executions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT DEFAULT 'pending',         -- pending, completed, error
  total_campaigns INT DEFAULT 0,
  total_adsets INT DEFAULT 0,
  total_ads INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE facebook_ads_manager.bulk_executions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_all" ON facebook_ads_manager.bulk_executions
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
